# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaslave', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='GameSave',
        ),
    ]
