# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaslave', '0002_auto_20161208_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesave',
            name='currentTileMap',
        ),
        migrations.AddField(
            model_name='gamesave',
            name='currentGameMap',
            field=models.IntegerField(default=0),
        ),
    ]
