# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaslave', '0003_auto_20161215_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('object_id', models.IntegerField()),
                ('content', models.CharField(max_length=128)),
            ],
        ),
    ]
